version: 2
services:
  - name: zideebot-whatsapp
    type: web
    instance_type: nano
    ports:
      - port: 8000
        protocol: http
    env:
      - NODE_ENV=production
      - PORT=8000
    build:
      commands:
        - npm install
    run:
      command: node index.js
    regions:
      - was
    scaling:
      min: 1
      max: 1
    health_check:
      http:
        path: /health
        port: 8000
